//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by alienfx-gui.rc
//
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_RAM                         104
#define IDM_EXIT                        105
#define IDS_CPU                         105
#define IDS_HDD                         106
#define IDS_NET                         107
#define IDS_GPU                         108
#define IDS_FANS                        109
#define IDS_TEMP                        110
#define IDS_BATT                        111
#define IDS_A_HDD                       112
#define IDS_A_NET                       113
#define IDS_A_HOT                       114
#define IDS_A_OOM                       115
#define IDS_TYPE_BREATH                 116
#define IDS_TYPE_SPECTRUM               117
#define IDS_TYPE_RAINBOW                118
#define IDS_A_LOWBATT                   119
#define IDS_HOMEPAGE                    120
#define IDS_UPDATEPAGE                  121
#define IDS_TAB_COLOR                   122
#define IDS_TAB_EVENTS                  123
#define IDS_TAB_AMBIENT                 124
#define IDS_TAB_HAPTICS                 125
#define IDS_TAB_GROUPS                  126
#define IDS_TAB_PROFILES                127
#define IDS_TAB_DEVICES                 128
#define IDS_TAB_FANS                    129
#define IDS_TAB_SETTINGS                130
#define IDD_MAINWINDOW                  131
#define IDI_ALIENFXGUI                  132
#define IDD_DIALOG_COLORS               133
#define IDD_DIALOG_EVENTS               134
#define IDD_DIALOG_AMBIENT              135
#define IDD_DIALOG_HAPTICS              136
#define IDD_DIALOG_GROUPS               137
#define IDD_DIALOG_PROFILES             138
#define IDD_DIALOG_DEVICES              139
#define IDD_DIALOG_FAN                  140
#define IDD_DIALOG_SETTINGS             141
#define IDS_TYPE_COLOR                  142
#define IDS_TYPE_PULSE                  143
#define IDS_TYPE_MORPH                  144
#define IDC_ALIENFXGUI                  146
#define IDI_ALIENFX_ON                  147
#define IDI_ALIENFX_OFF                 148
#define IDI_ALIENFX_DIM                 149
#define IDR_MENU_TRAY                   150
#define IDD_DIALOG_AUTODETECT           154
#define IDC_TAB_MAIN                    1000
#define IDC_COMBO_POWER                 1000
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_TEMP_LIST                   1002
#define IDC_BUTTON3                     1002
#define IDC_FAN_LIST                    1003
#define IDC_BUTTON4                     1003
#define IDC_BUTTON5                     1004
#define IDC_FREQ                        1004
#define IDC_BUTTON_C1                   1005
#define IDC_BUTTON6                     1005
#define IDC_BUTTON7                     1006
#define IDC_SPEED1                      1007
#define IDC_BUT_RESET                   1007
#define IDC_BUTTON8                     1007
#define IDC_BUTTON9                     1008
#define IDC_LENGTH1                     1009
#define IDC_CHECK_NOEVENT               1009
#define IDC_BUTTON10                    1009
#define IDC_CHECK_POWER                 1010
#define IDC_BUTTON11                    1010
#define IDC_CHECK_PERF                  1011
#define IDC_BUTTON12                    1011
#define IDC_CHECK_STATUS                1012
#define IDC_LIGHTS                      1013
#define IDC_COUNTERLIST                 1013
#define IDC_SLIDER_GPU                  1013
#define IDC_STATUSLIST                  1014
#define IDC_SLIDER_LOWCUT               1014
#define IDC_DEVICES                     1015
#define IDC_BUTTON_LPC                  1015
#define IDC_STARTW                      1016
#define IDC_BUTTON_HPC                  1016
#define IDC_STARTM                      1017
#define IDC_BUTTON_REMOVE               1017
#define IDC_AUTOREFRESH                 1018
#define IDC_SLIDER_HICUT                1018
#define IDC_BUTTON_REFRESH              1021
#define IDC_BUTTON_MINIMIZE             1022
#define IDC_LIGHTS_E                    1023
#define IDC_SHOWAXIS                    1023
#define IDC_BUTTON_SAVE                 1024
#define IDC_LEVELS                      1025
#define IDC_LIGHTID                     1026
#define IDC_CHECK1                      1026
#define IDC_BUTTON_ADDL                 1027
#define IDC_CHECK2                      1027
#define IDC_BUTTON_REML                 1028
#define IDC_CHECK3                      1028
#define IDC_BUTTON_CM1                  1029
#define IDC_BUTTON_DEVRESET             1029
#define IDC_CHECK4                      1029
#define IDC_BUTTON_CM2                  1030
#define IDC_BUTTON_ADDG                 1030
#define IDC_CHECK5                      1030
#define IDC_BUTTON_CM3                  1031
#define IDC_BATTDIM                     1031
#define IDC_BUTTON_REMG                 1031
#define IDC_CHECK6                      1031
#define IDC_SLIDER_DIMMING              1032
#define IDC_BUTTON_CM4                  1032
#define IDC_BUT_GRP_UP                  1032
#define IDC_CHECK7                      1032
#define IDC_BUTTON_SETALL               1033
#define IDC_BUTTON_CM5                  1033
#define IDC_REMOVEPROFILE               1033
#define IDC_SCREENOFF                   1033
#define IDC_BUT_GRP_DOWN                1033
#define IDC_CHECK8                      1033
#define IDC_BUTTON_CM6                  1034
#define IDC_PROFILES                    1034
#define IDC_POWER_DIM                   1034
#define IDC_CHECK9                      1034
#define IDC_ADDPROFILE                  1035
#define IDC_CHECK10                     1035
#define IDC_CHECK11                     1036
#define IDC_BUT_PROFILESWITCH           1037
#define IDC_CHECK12                     1037
#define IDC_AWCC                        1038
#define IDC_RADIO_PRIMARY               1038
#define IDC_BUTTON_TESTCOLOR            1039
#define IDC_ESIFTEMP                    1039
#define IDC_RADIO_SECONDARY             1039
#define IDC_TYPE1                       1040
#define IDC_BUTTON_EFFCLR1              1040
#define IDC_BUTTON_EFFCLR2              1041
#define IDC_SLIDER_BR                   1041
#define IDC_FANCONTROL                  1042
#define IDC_SYSLINK_HOMEPAGE            1043
#define IDC_ISPOWERBUTTON               1044
#define IDC_MINPVALUE                   1045
#define IDC_CUTLEVEL                    1046
#define IDC_BUTTON_RESET                1046
#define IDC_STATUS_BLINK                1047
#define IDC_STATIC_VERSION              1048
#define IDC_CHECK_LON                   1049
#define IDC_OFFPOWERBUTTON              1051
#define IDC_CHECK_GAMMA                 1052
#define IDC_BUTTON_RESETCOLOR           1053
#define IDC_LIST_APPLICATIONS           1055
#define IDC_CHECK_DEFPROFILE            1056
#define IDC_DEVICE_STATUS               1058
#define IDC_APP_RESET                   1059
#define IDC_APP_BROWSE                  1060
#define IDC_EFFECTS_LIST                1066
#define IDC_BUT_ADD_EFFECT              1068
#define IDC_BUTT_REMOVE_EFFECT          1069
#define IDC_CHECK_PROFDIM               1071
#define IDC_CHECK_FOREGROUND            1073
#define IDC_BUT_PROFRESET               1076
#define IDC_LIST_PROFILES               1077
#define IDC_LIST_LIGHTS                 1079
#define IDC_CHECK_INDICATOR             1080
#define IDC_GROUPS                      1082
#define IDC_LIST_INGROUP                1083
#define IDC_BUT_ADDTOG                  1084
#define IDC_BUT_DELFROMG                1085
#define IDC_GAUGE                       1085
#define IDC_GLOBAL_EFFECT               1088
#define IDC_SLIDER_TEMPO                1089
#define IDC_BUT_LOADMAP                 1090
#define IDC_BUT_SAVEMAP                 1091
#define IDC_CHECK_FANPROFILE            1092
#define IDC_EFFECT_MODE                 1093
#define IDC_RADIO_OUTPUT                1094
#define IDC_RADIO_INPUT                 1095
#define IDC_FAN_CURVE                   1096
#define IDC_STATIC_BOOST                1097
#define IDC_COMBO_EFFMODE               1098
#define IDC_CHECK_EFFECTS               1099
#define IDC_CHECK_PRIORITY              1100
#define IDC_CHECK_EXCEPTION             1101
#define IDC_LIST_SUG                    1103
#define IDC_BUT_DETECT                  1104
#define ID_TRAYMENU_RESTORE             32772
#define ID_TRAYMENU_LIGHTSON            32773
#define ID_TRAYMENU_DIMLIGHTS           32774
#define ID_TRAYMENU_EXIT                32775
#define ID_TRAYMENU_REFRESH             32776
#define ID_ACC_COLOR                    32777
#define ID_ACC_EVENTS                   32778
#define ID_ACC_SETTINGS                 32779
#define ID_TRAYMENU_MONITORING          32785
#define ID_ACC_DEVICES                  32786
#define ID_TRAYMENU_PROFILESWITCH       32788
#define ID_TRAYMENU_PROFILES            32789
#define ID_ACC_PROFILES                 32790
#define ID_TRAYMENU_PROFILE_SELECTED    32791
#define ID_TRAYMENU_MONITORING_SELECTED 32792
#define ID_ACC_AMBIENT                  32797
#define ID_ACC_HAPTICS                  32798
#define ID_ACC_FANS                     32799
#define ID_ACC_GROUPS                   32800
#define ID_TRAYMENU_ENABLEEFFECTS       32802
#define ID_CHECKUPDATE                  32803
#define IDM_CHECKUPDATE                 32804
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
