//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by alienfx-gui.rc
//
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDD_GRIDBLOCK                   130
#define IDD_MAINWINDOW                  131
#define IDI_ALIENFXGUI                  132
#define IDD_DIALOG_COLORS               133
#define IDD_DIALOG_EVENTS               134
#define IDD_DIALOG_AMBIENT              135
#define IDD_DIALOG_HAPTICS              136
#define IDD_DIALOG_PROFILES             138
#define IDD_DIALOG_DEVICES              139
#define IDD_DIALOG_FAN                  140
#define IDD_DIALOG_SETTINGS             141
#define IDC_ALIENFXGUI                  146
#define IDI_ALIENFX_ON                  147
#define IDI_ALIENFX_OFF                 148
#define IDI_ALIENFX_DIM                 149
#define IDR_MENU_TRAY                   150
#define IDD_DIALOG_AUTODETECT           154
#define IDD_DIALOG_LIGHTS               156
#define IDD_ZONESELECTION               158
#define IDD_LIGHT_TEMPLATE              159
#define IDD_DIALOG_ADDGROUP             160
#define IDD_DIALOG_WHITE                161
#define IDD_DIALOG_GRIDEFFECT           163
#define IDD_DIALOG_KEY                  164
#define IDD_DIALOG_DEVICEEFFECTS        165
#define IDD_SELECTFROMLIST              166
#define IDC_TAB_MAIN                    1000
#define IDC_COMBO_POWER                 1000
#define IDC_TEMP_LIST                   1002
#define IDC_BUT_NEXT                    1002
#define IDC_FAN_LIST                    1003
#define IDC_BUT_PREV                    1004
#define IDC_BUTTON_C1                   1005
#define IDC_EDIT_NAME                   1005
#define IDC_SPEED1                      1007
#define IDC_LENGTH1                     1009
#define IDC_CHECK_NOEVENT               1009
#define IDC_BUT_CLEAR                   1012
#define IDC_EVENT_SOURCE                1014
#define IDC_BUTTON_LPC                  1015
#define IDC_STARTW                      1016
#define IDC_BUTTON_HPC                  1016
#define IDC_MAX_RESET                   1016
#define IDC_STARTM                      1017
#define IDC_BUTTON_REMOVE               1017
#define IDC_BUT_RESETBOOST              1017
#define IDC_LIST_DEV                    1018
#define IDC_HOTKEYS                     1018
#define IDC_BUT_LAST                    1019
#define IDC_BUTTON_REFRESH              1021
#define IDC_BUTTON_MINIMIZE             1022
#define IDC_BUTTON_SAVE                 1024
#define IDC_LEVELS                      1025
#define IDC_LIGHTID                     1026
#define IDC_BATTDIM                     1031
#define IDC_BUTTON_COLORFROM            1031
#define IDC_SLIDER_DIMMING              1032
#define IDC_REMOVEPROFILE               1033
#define IDC_SCREENOFF                   1033
#define IDC_PROFILES                    1034
#define IDC_POWER_DIM                   1034
#define IDC_BUTTON_COLORTO              1034
#define IDC_ADDPROFILE                  1035
#define IDC_BUT_PROFILESWITCH           1037
#define IDC_AWCC                        1038
#define IDC_RADIO_PRIMARY               1038
#define IDC_BUTTON_TESTCOLOR            1039
#define IDC_ESIFTEMP                    1039
#define IDC_RADIO_SECONDARY             1039
#define IDC_TYPE1                       1040
#define IDC_BUTTON_EFFCLR1              1040
#define IDC_BUTTON_EFFCLR2              1041
#define IDC_SLIDER_BR                   1041
#define IDC_FANCONTROL                  1042
#define IDC_BUTTON_EFFCLR3              1042
#define IDC_SYSLINK_HOMEPAGE            1043
#define IDC_BUTTON_EFFCLR4              1043
#define IDC_ISPOWERBUTTON               1044
#define IDC_CUTLEVEL                    1046
#define IDC_BUTTON_RESET                1046
#define IDC_STATUS_BLINK                1047
#define IDC_STATIC_VERSION              1048
#define IDC_CHECK_LON                   1049
#define IDC_OFFPOWERBUTTON              1051
#define IDC_CHECK_GAMMA                 1052
#define IDC_LIST_APPLICATIONS           1055
#define IDC_CHECK_DEFPROFILE            1056
#define IDC_APP_RESET                   1059
#define IDC_APP_BROWSE                  1060
#define IDC_LEFFECTS_LIST               1066
#define IDC_BUT_ADD_EFFECT              1068
#define IDC_BUT_REMOVE_EFFECT           1069
#define IDC_CHECK_PROFDIM               1071
#define IDC_CHECK_FOREGROUND            1073
#define IDC_BUT_PROFRESET               1076
#define IDC_LIST_PROFILES               1077
#define IDC_CHECK_INDICATOR             1080
#define IDC_GLOBAL_EFFECT               1088
#define IDC_SLIDER_TEMPO                1089
#define IDC_BUT_LOADMAP                 1090
#define IDC_GLOBAL_KEYEFFECT            1090
#define IDC_BUT_SAVEMAP                 1091
#define IDC_SLIDER_KEYTEMPO             1091
#define IDC_CHECK_FANPROFILE            1092
#define IDC_EFFECT_MODE                 1093
#define IDC_RADIO_OUTPUT                1094
#define IDC_RADIO_INPUT                 1095
#define IDC_FAN_CURVE                   1096
#define IDC_COMBO_EFFMODE               1098
#define IDC_CHECK_EFFECTS               1099
#define IDC_CHECK_PRIORITY              1100
#define IDC_CHECK_EXCEPTION             1101
#define IDC_BUT_DETECT                  1104
#define IDC_CHECK_DIM                   1105
#define IDC_INFO_VID                    1106
#define IDC_SLIDER_RED                  1110
#define IDC_SLIDER_GREEN                1111
#define IDC_SLIDER_BLUE                 1112
#define IDC_FREQ_GROUP                  1121
#define IDC_BUT_ADD_GROUP               1122
#define IDC_BUT_REM_GROUP               1123
#define IDC_FC_LABEL                    1123
#define IDC_AC_BOOST                    1124
#define IDC_DC_BOOST                    1125
#define IDC_VAL_CPU                     1126
#define IDC_VAL_RAM                     1127
#define IDC_CHECK_UPDATE                1127
#define IDC_VAL_GPU                     1128
#define IDC_BUTTON_ZONE                 1128
#define IDC_VAL_PWR                     1129
#define IDC_SLIDER_HSCALE               1129
#define IDC_VAL_FAN                     1130
#define IDC_SLIDER_VSCALE               1130
#define IDC_BUT_COPYACTIVE              1130
#define IDC_BUT_OVER                    1130
#define IDC_VAL_NET                     1131
#define IDC_OFFONBATTERY                1131
#define IDC_VAL_BAT                     1132
#define IDC_FAN_RESET                   1132
#define IDC_VAL_TEMP                    1133
#define IDC_TAB_LIGHTS                  1133
#define IDC_STATIC_EFFECTS              1134
#define IDC_TAB_DEV_GRID                1135
#define IDC_BUT_FIRST                   1137
#define IDC_EDIT_GRID                   1138
#define IDC_TAB_COLOR_GRID              1139
#define IDC_BUT_ADD_ZONE                1140
#define IDC_BUT_DEL_ZONE                1141
#define IDC_AMB_BUTTON_ZONE             1142
#define IDC_LIST_ZONES                  1143
#define IDC_BUT_CLEARGRID               1144
#define IDC_STATIC_ZONES                1145
#define IDC_STATIC_ZONE_LABEL           1146
#define IDC_STATIC_CONTROLS             1146
#define IDC_CHECK_SPECTRUM              1149
#define IDC_COMBO_GAUGE                 1150
#define IDC_CP_COLORS                   1151
#define IDC_CP_EVENTS                   1152
#define IDC_CP_AMBIENT                  1153
#define IDC_CP_HAPTICS                  1154
#define IDC_LIST_GROUPS                 1155
#define IDC_CP_FANS                     1155
#define IDC_LIST_FOUND                  1156
#define IDC_CP_GRID                     1156
#define IDC_BUT_WHITE                   1158
#define IDC_CHECK_REVERSE               1159
#define IDC_CHECK_LIGHTNAMES            1161
#define IDC_COMBO_TRIGGERKEY            1162
#define IDC_TRIGGER_POWER_AC            1163
#define IDC_TRIGGER_POWER_BATTERY       1164
#define IDC_SLIDER_SPEED                1168
#define IDC_CHECK_CIRCLE                1169
#define IDC_CHECK_RANDOM                1170
#define IDC_SLIDER_WIDTH                1171
#define IDC_COMBO_TRIGGER               1172
#define IDC_COMBO_GEFFTYPE              1173
#define IDC_BUT_GECOLOR                 1175
#define IDC_BUT_KEY                     1176
#define IDC_DE_LIST                     1178
#define IDC_DEV_EFFECT                  1179
#define IDC_BUT_DEVCLEAR                1179
#define IDC_EVENT_TYPE                  1180
#define IDC_BUT_EVENT_DOWN              1181
#define IDC_BUTT_REMOVE_EVENT           1182
#define IDC_EVENTS_LIST                 1183
#define IDC_BUT_ADD_EVENT               1184
#define IDC_CHECK_PHASE                 1184
#define IDC_BUTT_EVENT_UP               1185
#define IDC_CHECK_BACKGROUND            1185
#define IDC_COLORS_LIST                 1186
#define IDC_BUT_ADD_COLOR               1187
#define IDC_BUT_REMOVE_COLOR            1188
#define IDC_LIGHTS_LIST                 1191
#define IDC_BUT_FROMLIST                1192
#define IDC_BUT_LIGHTSAPPLY             1194
#define IDC_BUT_LIGHTSRESET             1195
#define ID_TRAYMENU_RESTORE             32772
#define ID_TRAYMENU_LIGHTSON            32773
#define ID_TRAYMENU_DIMLIGHTS           32774
#define ID_TRAYMENU_EXIT                32775
#define ID_TRAYMENU_REFRESH             32776
#define ID_TRAYMENU_MONITORING          32786
#define ID_TRAYMENU_PROFILESWITCH       32788
#define ID_TRAYMENU_PROFILES            32789
#define ID_TRAYMENU_PROFILE_SELECTED    32791
#define ID_TRAYMENU_MONITORING_SELECTED 32792
#define ID_TRAYMENU_ENABLEEFFECTS       32802
#define IDM_CHECKUPDATE                 32804
#define IDM_HELP                        32807
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
